# Scans the music folder and writes music/playlist.js for index.html.
$music = Join-Path $PSScriptRoot 'music'
if (-not (Test-Path $music)) { New-Item -ItemType Directory -Path $music | Out-Null }
$exts = @('.mp3', '.m4a', '.aac', '.ogg', '.oga', '.opus', '.wav', '.flac', '.webm')
$files = @(Get-ChildItem -Path $music -Recurse -File | Where-Object { $exts -contains $_.Extension.ToLower() } | Sort-Object FullName)
$lines = foreach ($f in $files) {
  $rel = $f.FullName.Substring($music.Length + 1).Replace('\', '/').Replace('"', '\"')
  '  "' + $rel + '",'
}
$body = "// Generated by update-playlist.bat. Paths are relative to the music folder.`nwindow.PLAYLIST = [`n" + ($lines -join "`n") + "`n];`n"
[IO.File]::WriteAllText((Join-Path $music 'playlist.js'), $body, (New-Object Text.UTF8Encoding $false))
Write-Host ("{0} track(s) written to music/playlist.js" -f $files.Count)
